title: garlandthompsonjr
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.2089151
  brandStrength: 0.9375
  lightness: 0.2969925
  brandColors:
    - '#2f2d30'
    - '#5c565a'
    - '#fe4042'
    - '#acd1fe'
    - '#0a6fff'
  rhythmicContrast: 0.8694951
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: garlandthompsonjr
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.66602
layout_spectrum: 0.4419979
