name: garlandthompsonjr
favicon: null
layout_spectrum: 1
typography_spectrum: 0.66602
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2f2d30'
    - '#5c565a'
    - '#fe4042'
    - '#acd1fe'
    - '#0a6fff'
  brandStrength: 0.9375
  lightness: 0.06124411732889712
  saturation: 0.7696100850589573
  rhythmicContrast: 0.2601869481150061
purpose: []
